### ISSUE TITLE
为什么。。。指针和三角形都是用canvas画出来的。。。？这样有必要吗

### ISSUE THREAD

**Issue by patrickKXMD** [AvatarQing/MiClockView#1]

**Comment by AvatarQing** [comment]
简单图形能画就画啊，大小长度也都好调，用图片的话适配不同屏幕的时候会失真吧

**Comment by patrickKXMD** [comment]
图片适配好了是不会失真的~都canvas画的话，太累了，哈哈
另外，用DashPathEffect会导致首尾不会刚好贴合，还有没有什么更好的解决办法？

**Comment by AvatarQing** [comment]
其实还没有好的解决办法。。刚才又测了下，在400x854的机子上没这个问题，在1080p的机子上会有这个问题，估计和虚线的宽度、间隔值有关系

**Comment by xiaomeixw** [comment]
自定义VIEW一般都是canvas画控件....小米的工程师在实现该特效view时也是代码绘制的....
