### ISSUE TITLE
小时3,6,9,12绘制问题

### ISSUE THREAD

**Issue by benjious** [AvatarQing/MiClockView#3]
楼主可以讲解一下小时3.6.9.12文本定位的问题吗？？
12的（x，y）中的y看不是很明白
`scaleTextDrawCoordinates[0][0] = topTextBound.left;
		scaleTextDrawCoordinates[0][1] = topTextBound.top + (topTextBound.bottom - topTextBound.top) / 2 - (fm.bottom - fm.top) / 2 - fm.top;`
这段代码： 
` (topTextBound.bottom - topTextBound.top) / 2 - (fm.bottom - fm.top) / 2 - fm.top;`代表的是什么呢
？

**Comment by AvatarQing** [comment]
canvas.drawText()的时候计算text的baseline的y坐标，这个计算方式我忘了在哪查来的，你搜搜关于drawText时baseline的计算的文章

**Comment by benjious** [comment]
好的，最近就是被baseline搞到头都大了
