### ISSUE TITLE
时钟秒的线条绘制问题

### ISSUE THREAD

**Issue by benjious** [AvatarQing/MiClockView#4]
楼主看了很久“秒”线条的绘制，就是一个很多条线条表示秒的绘制那里，不是很明白，为何实现用的是： 
`canvas.save();

		translateCanvas(canvas, 0f, 0f, zDepthDashRing);
		canvas.drawArc(boundTimeRing, 0, 359.5f, false, paintBgRing);
		canvas.drawArc(boundTimeRing, 0, 359.5f, false, paintProgressRing);
		canvas.rotate(rotateSecondPointer, centerX, centerY);
		//画三角形
		canvas.drawPath(pathTriangle, paintTriangle);
		canvas.restore();`
而不是用 `canvas.drawLine() `，我想问一下楼主“秒”线条的实现思路是怎么样的，`canvas.drawArc()`不是绘制圆弧的吗？

**Comment by AvatarQing** [comment]
思路就是画一个只有边的圆，并且只画虚线，线的宽度粗一点，就是现在的效果，这种画法比较简单

**Comment by benjious** [comment]
感谢，明白了
